"""Turn a :class:`Project` into format-independent document specs (``DocSpec``).

A ``DocSpec`` is a title plus an ordered list of ``Block`` tuples. The exporters
in :mod:`.exporters` render a ``DocSpec`` to DOCX / ODT / PDF; the interactive
HTML transcript is built separately in :mod:`.export_html`.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, List, Tuple

from .model import Project, Severity

# Block = (kind, payload). kinds:
#   "h1"/"h2"/"h3" -> str
#   "p"            -> str
#   "note"         -> str            (rendered as an indented / boxed remark)
#   "meta"         -> List[(label, value)]
#   "bullets"      -> List[str]
#   "numbered"     -> List[str]
#   "speaker"      -> (speaker: str, text: str, timestamp: str)
#   "table"        -> (headers: List[str], rows: List[List[str]])
#   "link"         -> (text: str, target: str)
#   "hr"           -> None
#   "pagebreak"    -> None
Block = Tuple[str, Any]


@dataclass
class DocSpec:
    title: str
    blocks: List[Block] = field(default_factory=list)

    def add(self, kind: str, payload: Any = None) -> None:
        self.blocks.append((kind, payload))


def _fmt_ts(sec: float | None) -> str:
    if sec is None:
        return ""
    sec = max(0, int(sec))
    m, s = divmod(sec, 60)
    h, m = divmod(m, 60)
    return f"{h}:{m:02d}:{s:02d}" if h else f"{m:02d}:{s:02d}"


def _provenance_blocks(project: Project) -> List[Block]:
    a = project.answers
    rows = [
        ("Source recording", project.origin or project.media_path),
        ("Transcribed", "local Whisper (faster-whisper)"),
        ("Speaker separation",
         "pyannote.audio" if project.transcript.diarized else "not applied (single speaker)"),
        ("Word alignment",
         "forced alignment" if project.transcript.aligned else "Whisper estimate"),
        ("Analysis model", "local Qwen3" if a.wants_llm() else "n/a"),
        ("Generated by", "Meeting Scribe - all processing local"),
    ]
    if project.session_label:
        rows.append(("Session", project.session_label))
    return [("meta", rows)]


# --------------------------------------------------------------------------- #
#  Transcript                                                                 #
# --------------------------------------------------------------------------- #
def build_transcript(project: Project, named: bool) -> DocSpec:
    t = project.transcript
    kind = "identified" if named else "generic"
    title = f"{project.minutes.title if project.minutes else 'Meeting'} - Transcript"
    spec = DocSpec(title=title)
    spec.add("h1", title)
    spec.add("p", f"Speaker attribution: {kind}. "
                  f"Duration {_fmt_ts(t.duration)}. Language: {t.language}.")
    spec.blocks += _provenance_blocks(project)

    if named:
        roster = [(s.label, s.display) for s in t.speakers]
        spec.add("h3", "Speakers")
        spec.add("meta", roster)

    spec.add("hr", None)
    spec.add("h2", "Transcript")
    for seg in t.segments:
        who = t.speaker_by_id(seg.speaker)
        if who is None:
            name = "Speaker"
        elif named:
            name = who.display
        else:
            name = who.label
        spec.add("speaker", (name, seg.text.strip(), _fmt_ts(seg.start)))

    _append_qc_summary(spec, project)
    return spec


# --------------------------------------------------------------------------- #
#  Minutes                                                                    #
# --------------------------------------------------------------------------- #
def build_minutes(project: Project, with_synopsis: bool) -> DocSpec:
    m = project.minutes
    assert m is not None
    spec = DocSpec(title=m.title or "Meeting Minutes")
    spec.add("h1", m.title or "Meeting Minutes")

    meta: List[Tuple[str, str]] = []
    if m.meeting_date:
        meta.append(("Date", m.meeting_date))
    if m.location:
        meta.append(("Location", m.location))
    meta.append(("Attendees", ", ".join(m.attendees) if m.attendees else "not recorded"))
    meta.append(("Recording length", _fmt_ts(project.transcript.duration)))
    spec.add("meta", meta)

    if with_synopsis and m.synopsis.strip():
        spec.add("h2", "Synopsis")
        spec.add("p", m.synopsis.strip())

    if m.agenda:
        spec.add("h2", "Agenda")
        spec.add("bullets", m.agenda)

    spec.add("h2", "Discussion")
    if m.discussion:
        for topic in m.discussion:
            spec.add("h3", topic.topic)
            spec.add("bullets", topic.points or ["(no detail captured)"])
    else:
        spec.add("p", "No discussion detail was captured.")

    if m.decisions:
        spec.add("h2", "Decisions")
        spec.add("bullets", m.decisions)

    if project.answers.wants_action_items() and project.action_items:
        spec.add("h2", "Action Items")
        spec.add("table", _action_table(project))
    elif m.next_steps:
        spec.add("h2", "Next Steps")
        spec.add("bullets", m.next_steps)

    if m.next_steps and project.action_items:
        spec.add("h2", "Other Next Steps")
        spec.add("bullets", m.next_steps)

    spec.blocks += _provenance_blocks(project)
    _append_qc_summary(spec, project)
    return spec


# --------------------------------------------------------------------------- #
#  Action items                                                               #
# --------------------------------------------------------------------------- #
def build_action_items(project: Project) -> DocSpec:
    spec = DocSpec(title="Action Items")
    ttl = f"{project.minutes.title} - Action Items" if project.minutes else "Action Items"
    spec.add("h1", ttl)
    if not project.action_items:
        spec.add("p", "No action items were identified in this meeting.")
        spec.blocks += _provenance_blocks(project)
        _append_qc_summary(spec, project)
        return spec

    spec.add("table", _action_table(project, include_source=True))
    spec.add("h3", "Sources")
    for i, it in enumerate(project.action_items, 1):
        src = it.source_quote or "(no quote captured)"
        at = f" [{_fmt_ts(it.source_time)}]" if it.source_time is not None else ""
        spec.add("p", f"{i}. “{src}”{at}")

    spec.blocks += _provenance_blocks(project)
    _append_qc_summary(spec, project)
    return spec


def _action_table(project: Project, include_source: bool = False):
    headers = ["#", "Task", "Owner", "Due", "Confidence"]
    rows = []
    for i, it in enumerate(project.action_items, 1):
        rows.append([
            str(i),
            it.task,
            it.owner or "(unassigned)",
            it.due or "(none)",
            f"{it.confidence:.0%}",
        ])
    return (headers, rows)


# --------------------------------------------------------------------------- #
#  Accuracy report                                                            #
# --------------------------------------------------------------------------- #
def build_qc_report(project: Project) -> DocSpec:
    r = project.qc
    spec = DocSpec(title="Accuracy Report")
    spec.add("h1", "Accuracy & Quality-Control Report")
    spec.add("meta", [
        ("Overall", "PASS - no blocking errors" if r.passed
         else f"ATTENTION - {len(r.errors)} error(s) to resolve"),
        ("Errors", str(len(r.errors))),
        ("Warnings", str(len(r.warnings))),
        ("Checks run", ", ".join(r.checks_run) or "none"),
    ])
    if not r.issues:
        spec.add("p", "All automated checks passed with no issues raised.")
        return spec

    order = {Severity.ERROR: 0, Severity.WARNING: 1, Severity.INFO: 2}
    for sev, heading in ((Severity.ERROR, "Errors"),
                         (Severity.WARNING, "Warnings"),
                         (Severity.INFO, "Notes")):
        items = [i for i in r.issues if i.severity == sev]
        if not items:
            continue
        spec.add("h2", heading)
        rows = [[i.category, i.detail, i.suggestion or ""] for i in items]
        spec.add("table", (["Category", "Finding", "Suggested fix"], rows))
    return spec


def _append_qc_summary(spec: DocSpec, project: Project) -> None:
    r = project.qc
    if not r.issues and not r.checks_run:
        return
    spec.add("hr", None)
    spec.add("h3", "Accuracy check summary")
    verdict = ("All automated accuracy checks passed."
               if r.passed and not r.warnings else
               f"{len(r.errors)} error(s) and {len(r.warnings)} warning(s) were "
               f"raised - see the accompanying Accuracy Report.")
    spec.add("note", verdict)
    if r.errors:
        spec.add("bullets", [f"[ERROR] {i.detail}" for i in r.errors[:8]])
